pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      # Replace with the name of your CI(s)
      - check-success=Test with pytest
      - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions: 
      merge:
        method: merge
